### ISSUE TITLE
Setup Application Fields

### ISSUE THREAD

**Issue by zacowan** [swamphacks/swamphacks-system#4]
### Task
Display all fields associated with each application type when a user navigates to that application. Each set of fields should be split up into manageable sections, each with a descriptive title.
### Steps
- [x] Display shared application fields
- [ ] Display hacker fields
- [ ] Display mentor fields
- [ ] Display volunteer fields
### Implementation
* Create a separate component for each section of fields
* Store the form data in state (see `useState`). I would **not** create a separate state hook for each field.
* Create a toggle for in-person/online attendance, display fields accordingly.
### Reference
https://ant.design/components/overview/
https://ant.design/components/form/
