### ISSUE TITLE
Setup Field Validation

### ISSUE THREAD

**Issue by zacowan** [swamphacks/swamphacks-system#5]
### Task
Validate all fields on each application to keep data clean. This is incredibly important and will help avoid a lot of technical debt in the future.
### Steps
- [ ] Validate shared fields
- [ ] Validate hacker fields
- [ ] Validate mentor fields
- [ ] Validate volunteer fields
### Reference
https://ant.design/components/overview/
https://ant.design/components/form/
