### ISSUE TITLE
Handle Form Submission

### ISSUE THREAD

**Issue by zacowan** [swamphacks/swamphacks-system#6]
### Task
Mock a form submission by validating and then logging all of the data. Once the form is submitted, the state should change to show a modal with success/failure. The user should then be able to navigate to the home page of the application portal. Coordinate with @nionata to ensure data is labeled properly to be sent to the API endpoint.
### Steps
- [ ] Validate and log data on form submission. If the data is not valid, show which fields need fixing.
- [ ] Show a modal after submission (success/fail based on response) 
- [ ] Allow navigation back to home page
### Reference
https://ant.design/components/overview/
https://ant.design/components/form/
